<template>
    <div>
        <div class="searchBox">
            <div class="sb_inputWrap">
                <input type="text" v-model="searchs" placeholder="제목 또는 아티스트 명을 입력하세요." @focusin="inputFocus" @focusout="inputFocusOut">
                <div class="focusLine"></div>
                <button class="sb_btn" @click="getId">api</button>
            </div>
        </div>
        <button @click="console.log(videos)">videos</button>
        <ul>
            <li class="musicList" v-for="item in videos" :key="item.id">
                <div class="ml_img_wrap">
                    <div class="ml_img">
                        <img class="ml_i_album" :src="item.thumbnail" alt="">
                        <div class="ml_i_cover" data-play="play">
                            <img class="ml_i_play"  src="/img/img/play.svg" alt="play" >
                            <img class="ml_i_pause"  src="/img/img/pause.svg" alt="pause" >
                            <img class="ml_i_replay"  src="/img/img/replay.svg" alt="replay">
                        </div>
                    </div>
                </div>
                <div class="ml_text_wrap">
                    <div class="ml_text">
                        <h5 class="ml_title">{{ item.title }}</h5>
                        <p class="ml_artist">{{ item.artist }}</p>
                    </div>
                    <div class="ml_player">
                        <div class="ml_p_bar">
                            <div class="bar_line"></div>
                        </div>
                        <p class="ml_p_current">00:00</p>
                        <p class="nl_p_duration" data-time="">
                            {{ item.duration[0] < 10? '0'+item.duration[0] : item.duration[0] }} : 
                            {{ !item.duration[1]? "00" : item.duration[1] < 10? '0'+item.duration[1] : item.duration[1] }}
                        </p>
                    </div>
                </div>
                <div class="ml_menu">
                    <button type="button" class="ml_m_add">플레이리스트에 추가</button>
                    <button type="button" class="ml_m_search">해당 곡이 들어간 플레이리스트 검색</button>
                </div>
            </li>
        </ul>
    </div>
</template>

<script setup>
import axios from 'axios';
import {ref as dataRef, get, child} from 'firebase/database';
import {useDatabase} from '../datasources/firebase.js'
import { onMounted, ref, reactive } from 'vue';
import store from '../store/store';
// common ------------------------------------------------------------------
const inputFocus = () => {
    const q1 = document.querySelector(".focusLine");
    const q2 = document.querySelector(".sb_btn");
    q1.style.width = '100%';
    q2.style.borderColor = 'rgb(255, 136, 0)';
}
const inputFocusOut = () => {
    const q1 = document.querySelector(".focusLine");
    const q2 = document.querySelector(".sb_btn");
    q1.style.width = '0%';
    q2.style.borderColor = '#aaa';
}
// API key 받아오기 ----------------------------------------------- //
let APIkey = ref('');
async function getKey(){
  const q = await get(child(dataRef(useDatabase), 'API_key'));
  if( q.exists()){
    console.log(q.val());
    APIkey = q.val();
  } else {
    const r = console.log('not has API key.') 
  }
}
onMounted(function(){
    getKey();
})
//----------------------------------------------------------------

let videos = ref([]);
onMounted(function(){
    videos.value = store.getters.getNowSearchMusic;
})
let searchs = ref('attention');

async function getId(){
    const res = await axios.get("https://www.googleapis.com/youtube/v3/search",{
        params: {
            part: 'snippet',
            type: 'video',
            key: APIkey,
            q: searchs.value + " Auto-generated by YouTube.",
            videoCategoryId: '10',
            videoSyndicated: 'true',
            maxResults: 5
        }
    });
    const dataArr = await res.data.items.map(item => ({
            id: item.id.videoId,
            title: item.snippet.title.replaceAll('&#39;',`'`),
            artist: (item.snippet.channelTitle).split(' - Topic')[0],
            thumbnail: item.snippet.thumbnails.high.url,
            url: `https://www.youtube.com/watch?v=${item.id.videoId}`
        }));

    const durationPromises = await dataArr.map(item => {
        return axios.get("https://www.googleapis.com/youtube/v3/videos", {
        params: {
            part: 'contentDetails',
            id: item.id,
            key: APIkey
        }})
    .then(response => response.data.items[0].contentDetails.duration);
    });

    Promise.all(durationPromises).then(durations => {
        dataArr.forEach((item, index) => {
        item.duration = durations[index].match(/[0-9]+/g);
    })}).then(res => videos.value = dataArr)

    store.commit('storeSearching',dataArr);
    console.log(videos.value);
    console.log(dataArr);
}
// ---------------------------------------------------------------------------
const playState = function(){
    const musicList = document.querySelectorAll(".musicList");
    musicList.forEach(v => {
        v.querySelector(".ml_i_play").addEventListener('click',function(){
            v.querySelector(".ml_p_bar").classList.add("playStart");
            v.querySelector(".ml_p_current").classList.add("playStart");
            this.classList.add("removed");
            v.querySelector(".ml_i_pause").classList.remove("removed");
        })
    })
}
</script>

<style scoped>
.musicList {
    position: relative;
    display: flex;
    align-items: center;
    gap: 1rem;
    border: 1px dashed tomato;
    width: 80%;
    height: max(14vh, 4rem);
    background-color: white;
    padding: 0.5em;
    margin: auto;
}
.ml_img_wrap {
    height: 100%;
}
.ml_img {
    border: 1px solid black;
    border-radius: 50%;
    height: 100%;
    aspect-ratio: 1/1;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    transition: .5s ease;
    background-color: white;
}
.ml_img:hover {
    box-shadow: 1px 2px 5px 0px #666;
}
.ml_i_cover {
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: rgba(255,255,255,0.5);
    opacity: 0.4;
    transition: .5s ease;
}
.ml_i_cover:hover {
    background-color: rgba(255,255,255,0.5);
    opacity: 1;
}
.ml_i_cover img {
    cursor: pointer;
    /* transform-origin: center;
    transform: scale(0.6,0.6); */
}
.ml_img img {
    display: block;
    height: 150%;
}
.ml_i_cover img.removed {
    display: none;
}
.stopRoll {
    animation-play-state: paused;
}
@keyframes rolling{
    from{ transform: rotateZ(0deg); }
    to{ transform: rotateZ(360deg); }
}
.ml_player {
    display: flex;
    align-items: center;
    gap: 1rem;
}
.ml_text_wrap{
    width: 100%;
    padding-right: 5%;
}
.ml_text {
    display: flex;
    align-items: center;
    gap: 2rem;
    margin-bottom: 1rem;
}
.ml_title {
    padding: 0px;
    margin: 0px;
    font-size: 150%;
}
.ml_artist {
    padding: 0px;
    margin: 0px;
}
.ml_p_bar {
    height: 0.5rem;
    overflow: hidden;
    background-color: #eee;
    width: 0;
    transition: .8s ease-in-out;
}
.ml_p_current {
    width: 0em;
    overflow: hidden;
    display: flex;
    justify-content: start;
    transition: .5s ease-in-out;
}
.ml_p_current.playStart {
    width: 3em;
}
.ml_p_bar.playStart {
    width: 100%;
}
.ml_player p{
    padding: 0px;
    margin: 0px;
}
.ml_menu button{
    width: 2rem;
    height: 2rem;
    border-radius: 50%;
    background-color: #ddd;  
    border: 0;
    font-size: 0px;
}
.ml_m_add {
    background: url('/img/img/plus.png') center/80% no-repeat;
    margin-bottom: 3px;
}
.ml_m_search {
    background: url('/img/img/search.svg') center/80% no-repeat;
}
.searchBox {
    position: relative;
    display: flex;
    justify-content: center;
}
.sb_inputWrap {
    width: 50%;
    position: relative;
}
.searchBox input {
    width: 100%;
    height: 2.5em;
    font-size: 100%;
    padding: 0.5em 10%;
    box-sizing: border-box;
    border: 0;
    border-bottom: 1px solid #aaa;
    outline: none;
}
.focusLine {
    position: absolute;
    bottom: 0;
    right: 0;
    width: 0;
    height: 1px;
    background-color: rgb(255, 136, 0);
    transition: .5s ease;
}
.sb_btn {
    font-size: 0px;
    position: absolute;
    right: 0;
    top: 0;
    border: 1px solid #aaaaaa;
    background: transparent url('/img/img/search.svg') center/2rem no-repeat;
    height: 100%;
    width: 5rem;
    cursor: pointer;
    transition: .5s ease;
}
.sb_btn:hover {
    background-color: rgba(255, 136, 0,0.6);
    border-color: transparent;
}
</style>