<template>
    <div>
        <input type="text" v-model="searchs">제목
        <button @click="getId">api</button>
        <ul>
            <li class="musicList" v-for="item in videos" :key="item.id">
                <img :src="item.thumbnail" width="200">
                <div>
                    <h4>{{ item.title }}</h4>
                    <h5>{{ item.artist }}</h5>
                    <p>{{ item.duration }}</p>
                </div>
            </li>
        </ul>
    </div>
</template>

<script setup>
import axios from 'axios';
import {ref as dataRef, get, child} from 'firebase/database';
import {useDatabase} from '../datasources/firebase.js'
import { onMounted, ref, reactive } from 'vue';
// API key 받아오기 ----------------------------------------------- //
let APIkey = ref('');
async function getKey(){
  const q = await get(child(dataRef(useDatabase), 'API_key'));
  if( q.exists()){
    console.log(q.val());
    APIkey = q.val();
  } else {
    const r = console.log('not has API key.') 
  }
}
onMounted(function(){
    getKey();
})
//----------------------------------------------------------------

let videos = ref([]);
let searchs = ref('attention');

async function getId(){
    const res = await axios.get("https://www.googleapis.com/youtube/v3/search",{
        params: {
            part: 'snippet',
            type: 'video',
            key: APIkey,
            q: searchs.value + " Auto-generated by YouTube.",
            videoCategoryId: '10',
            videoSyndicated: 'true',
            maxResults: 5,
        }
    });
    const dataArr = await res.data.items.map(item => {
        return{  id: item.id.videoId,
            title: item.snippet.title,
            artist: (item.snippet.channelTitle).split(' - Topic')[0],
            thumbnail: item.snippet.thumbnails.high.url,
            url: `https://www.youtube.com/watch?v=${item.id.videoId}`}
    });
    
    videos.value = await dataArr;
    console.log(videos.value);
}
</script>

<style scoped>
.musicList {
    display: flex;
}
</style>